stages:
  - build
  - deploy

build:
  stage: build
  image: maven:3.6.3-jdk-11
  script:
    - mvn --batch-mode -U -Dmaven.repo.local=.m2/repository -f app/pom.xml clean package
  cache:
    paths:
      - .m2/repository
  artifacts:
    paths:
      - app/target/bookInformation.jar
deploy:
  stage: deploy
  image: cytopia/ansible:2.9-tools
  only:
    - master
  script:
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - export ANSIBLE_ROLES_PATH=.galaxy/
    - chmod 600 "$SSH_KEY"
    - cp app/target/bookInformation.jar platform
    - cp $PRODUCTION_PROPERTIES platform/default.properties
    - cd platform
    - ansible-galaxy install -r requirements.yml --roles-path=.galaxy/
    - ansible-playbook deploySite.yml -i staging/production --private-key="$SSH_KEY"
  cache:
    paths:
      - .galaxy