image: docker:stable

services:
  - docker:dind

before_script:
  - docker info

build:
  only:
    - master
  script:
    - docker run --tty --rm --name my-maven-project -v "$(pwd)/app":/usr/src/mymaven -w /usr/src/mymaven maven:3.6.3-jdk-11 mvn clean package
  artifacts:
    paths:
      - app/target/bookInformation.jar