stages:
  - build
  - deploy

build:
  stage: build
  image: maven:3.6.3-jdk-11
  script:
    - mvn --batch-mode -U -s .m2/settings.xml -f app/pom.xml clean package
    - ls .m2/
  cache:
    paths:
      - .m2/repository #this path is relative to the current directory, eg, I can't reference /root/.m2, but only project/root/.m2
  artifacts:
    paths:
      - app/target/bookInformation.jar
deploy:
  stage: deploy
  image: cytopia/ansible:2.9-tools
  only:
    - master
  script:
    - chmod 600 "$SSH_KEY"
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - cp app/target/bookInformation.jar platform
    - cp "$PRODUCTION_PROPERTIES" platform
    - cd platform
    - ansible-playbook deploySite.yml -i staging/production --private-key="$SSH_KEY"