stages:
  - build
  - deploy

services:
  - docker:dind

build:
  stage: build
  image: maven:3.6.3-jdk-11
  script:
    - mvn --batch-mode -U -f app/pom.xml clean package
  cache:
    paths:
      - /root/.m2
  artifacts:
    paths:
      - app/target/bookInformation.jar
deploy:
  stage: deploy
  image: docker:stable
  only:
    - master
  script:
    - docker run --tty --rm --name my-maven-project -v "$(pwd)/app":/usr/src/mymaven -w /usr/src/mymaven maven:3.6.3-jdk-11 mvn clean package
#ansible-playbook deploySite.yml -i  --user=ec2-user --private-key=${ssh_key}staging/amiBuilder