---
- name: create directorys
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/var/www/html"
    - "/opt/certs"

- name: Install apache
  include_role:
    name: geerlingguy.apache
  vars:
    apache_remove_default_vhost: true
    apache_create_vhosts: true
    apache_mods_enabled:
      - rewrite.load
      - ssl.load
      - proxy.load
      - proxy_http.load
    apache_vhosts:
      - servername: "bookinformation.seshat.cc"
        documentroot: "/var/www/html"

- name: Set httpd_can_network_connect flag on and keep it persistent across reboots
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: Copy required files
  copy:
    src: "{{ item }}"
    dest: "/opt/certs/{{ item }}"
    owner: root
    group: root
    mode: 0700
  with_items:
    - bookinformation.seshat.cc.key
    - bookinformation.seshat.cc.csr
    - account.key

- name: "Create .well-known/acme-challenge directory"
  file:
    path: /var/www/html/.well-known/acme-challenge
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: "Begin Let's Encrypt challenges"
  acme_certificate:
    acme_directory: "https://acme-v02.api.letsencrypt.org/directory"
    acme_version: "2"
    account_key_src: "/opt/certs/account.key"
    account_email: "thomas@goodiemania.org"
    terms_agreed: 1
    challenge: "http-01"
    csr: "/opt/certs/bookinformation.seshat.cc.csr"
    dest: "/opt/certs/bookinformation.seshat.cc.crt"
    fullchain_dest: "/opt/certs/fullchain_bookinformation.seshat.cc.chain.crt"
    remaining_days: 91
  register: acme_challenge_your_domain

- name: "Implement http-01 challenge files"
  copy:
    content: "{{ acme_challenge_your_domain }}"
    dest: "/var/www/html/test"

- name: "Implement http-01 challenge files"
  copy:
    content: "{{ acme_challenge_your_domain['challenge_data'][item]['http-01']['resource_value'] }}"
    dest: "/var/www/html/{{ acme_challenge_your_domain['challenge_data'][item]['http-01']['resource'] }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  when: acme_challenge_your_domain["challenge_data"] is defined and (acme_challenge_your_domain["challenge_data"]|length>0)
  with_items:
      - "bookinformation.seshat.cc"
      - "www.bookinformation.seshat.cc"

- name: "Complete Let's Encrypt challenges"
  acme_certificate:
    acme_directory: "https://acme-v02.api.letsencrypt.org/directory"
    acme_version: "2"
    account_key_src: "/opt/certs/account.key"
    account_email: "thomas@goodiemania.org"
    challenge: "http-01"
    csr: "/opt/certs/bookinformation.seshat.cc.csr"
    dest: "/opt/certs/bookinformation.seshat.cc.crt"
    chain_dest: "/opt/certs/chain_bookinformation.seshat.cc.crt"
    fullchain_dest: "/opt/certs/fullchain_bookinformation.seshat.cc"
    data: "{{ acme_challenge_your_domain }}"

- name: Install apache
  include_role:
    name: geerlingguy.apache
  vars:
    apache_remove_default_vhost: true
    apache_create_vhosts: true
    apache_mods_enabled:
      - rewrite.load
      - ssl.load
      - proxy.load
      - proxy_http.load
    apache_vhosts_ssl:
      - servername: "bookinformation.seshat.cc"
        certificate_file: "/opt/certs/bookinformation.seshat.cc.crt"
        certificate_key_file: "/opt/certs/bookinformation.seshat.cc.key"
        certificate_chain_file: "/opt/certs/fullchain_bookinformation.seshat.cc"
        extra_parameters: |
          ProxyPass / http://127.0.0.1:7000/
          ProxyPassReverse / http://127.0.0.1:7000/
    apache_vhosts:
      - servername: "bookinformation.seshat.cc"
        documentroot: "/var/www/html"